/**
 * Atlas -- Capabilities Auto-Sync
 *
 * Reads CAPABILITIES declarations from each integration module and
 * regenerates .claude/rules/capabilities.md on startup. This ensures
 * the doc Atlas reads to decide "can I do X?" always matches the code.
 *
 * To add capabilities to a module:
 *   export const CAPABILITIES: CapabilityDeclaration = { ... }
 *
 * The sync runs on startup. If a module's capabilities change,
 * the next restart picks it up automatically.
 */

import { writeFileSync, readFileSync } from "fs";
import { join } from "path";
import { info, warn } from "./logger.ts";

export interface CapabilityDeclaration {
  section: string;        // e.g. "Meta Ads"
  description: string;    // e.g. "Graph API v21.0 (read + write)"
  can: string[];
  cannot: string[];
  commands?: string;      // e.g. "/ads, /adspend, /topcreative"
  notes?: string;         // extra context (monitoring thresholds, etc.)
  tags?: string;          // action tags like [GHL_NOTE:], [WP_POST:]
  runs?: string;          // cron schedule info
  state?: string;         // state files
  depends?: string;       // dependencies
  requires?: string;      // requirements
  module?: string;        // source module path for reference
}

// Registry of all capability declarations, populated by imports
const registry: CapabilityDeclaration[] = [];

export function registerCapabilities(cap: CapabilityDeclaration): void {
  // Replace if same section already registered (handles reload)
  const idx = registry.findIndex((c) => c.section === cap.section);
  if (idx >= 0) {
    registry[idx] = cap;
  } else {
    registry.push(cap);
  }
}

/**
 * Generate capabilities.md content from all registered declarations.
 */
function generateCapabilitiesDoc(): string {
  const lines: string[] = [
    "# Capabilities & Limitations Reference",
    "",
    "When asked \"can you do X?\" answer from this list INSTANTLY. Do NOT search source code.",
    "",
    "<!-- AUTO-GENERATED by src/capabilities.ts on startup. Do not edit manually. -->",
    "<!-- To update: modify the CAPABILITIES export in the relevant integration module. -->",
    "",
  ];

  for (const cap of registry) {
    lines.push(`## ${cap.section} - ${cap.description}`);
    lines.push(`CAN: ${cap.can.join(", ")}`);
    lines.push(`CANNOT: ${cap.cannot.join(", ")}`);
    if (cap.commands) lines.push(`COMMANDS: ${cap.commands}`);
    if (cap.tags) lines.push(`TAGS: ${cap.tags}`);
    if (cap.runs) lines.push(`RUNS: ${cap.runs}`);
    if (cap.state) lines.push(`STATE: ${cap.state}`);
    if (cap.depends) lines.push(`DEPENDS ON: ${cap.depends}`);
    if (cap.requires) lines.push(`REQUIRES: ${cap.requires}`);
    if (cap.notes) lines.push(`${cap.notes}`);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Sync capabilities to disk. Called on startup after all modules register.
 */
export function syncCapabilities(projectRoot: string): void {
  if (registry.length === 0) {
    warn("capabilities", "No capabilities registered, skipping sync");
    return;
  }

  const capPath = join(projectRoot, ".claude", "rules", "capabilities.md");
  const newContent = generateCapabilitiesDoc();

  // Only write if content actually changed (avoid unnecessary disk writes)
  try {
    const existing = readFileSync(capPath, "utf-8");
    if (existing === newContent) {
      info("capabilities", `Capabilities in sync (${registry.length} modules)`);
      return;
    }
  } catch {
    // File doesn't exist yet, that's fine
  }

  writeFileSync(capPath, newContent);
  info("capabilities", `Synced capabilities.md from ${registry.length} modules`);
}
