/**
 * Atlas -- Capability Registry
 *
 * Single source of truth for what Atlas can and cannot do.
 * Each integration's capabilities are declared here, co-located
 * with their module path so changes are easy to find and update.
 *
 * On startup, syncCapabilities() writes these to .claude/rules/capabilities.md.
 * That file is auto-generated. Never edit it by hand.
 *
 * HOW TO UPDATE:
 *   1. Add/change a function in an integration module (e.g. meta.ts)
 *   2. Update the matching entry below
 *   3. Restart Atlas -- capabilities.md auto-updates
 *
 * The startup log will confirm: "Synced capabilities.md from N modules"
 */

import { registerCapabilities, type CapabilityDeclaration } from "./capabilities.ts";

const ALL_CAPABILITIES: CapabilityDeclaration[] = [
  {
    section: "GHL (GoHighLevel)",
    description: "PIT token, API v2021-07-28",
    can: [
      "search contacts",
      "get contact by ID",
      "read pipeline/opportunities/stages",
      "read conversations/messages (last 15)",
      "add notes",
      "create/complete tasks",
      "add/remove tags",
      "enroll/remove from workflows",
      "list custom fields (read)",
      "list workflows",
      "get appointments",
      "ops snapshot (close rate, show rate, stale leads, no-shows)",
      "recent leads (7d)",
    ],
    cannot: [
      "write custom field values (API doesn't support via PIT)",
      "create/manage trigger links (not in API)",
      "send SMS or email directly (only via workflow enrollment)",
      "modify opportunity stage/status/value",
      "update contact fields (email, phone, name)",
      "delete anything",
      "access OAuth-only endpoints (calendar may fail)",
    ],
    notes: "WORKAROUND for custom values/trigger links: must be done manually in GHL dashboard, or build a workflow that sets the values and enroll via [GHL_WORKFLOW:].",
    module: "src/ghl.ts",
  },
  {
    section: "GHL Social Planner",
    description: "Social media posting via GHL Social Planner API (PIT token, requires socialplanner/* scopes)",
    can: [
      "list connected social accounts (Facebook, Instagram, GBP, LinkedIn, TikTok, Twitter)",
      "create draft posts for review before publishing",
      "schedule posts to specific date/time",
      "multi-platform posting in one call",
      "include images/video via public URLs",
      "GBP posts with CTA buttons (book, learn_more, call, etc.)",
      "list/search existing posts by status",
      "update post status (draft -> scheduled -> publish)",
      "CSV bulk upload for batch scheduling",
    ],
    cannot: [
      "upload media directly (must be publicly accessible URLs)",
      "create/manage social account connections (done in GHL dashboard)",
    ],
    notes: "Posts default to draft status. Use [GHL_SOCIAL: text | platforms=facebook,instagram,google | media=url | schedule=ISO-date] tag. GBP posting via Social Planner bypasses the Google API rejection issue.",
    module: "src/ghl-social.ts",
    commands: ["/social (list accounts, draft posts)"],
    tags: ["[GHL_SOCIAL: summary | platforms=... | media=... | schedule=... | gbp_cta=...]"],
  },
  {
    section: "Google",
    description: "OAuth2 (Derek read+draft+calendar+contacts, Atlas send-only)",
    can: [
      "list unread emails (up to 10)",
      "read full email body by ID",
      "create drafts (Derek)",
      "send email (Atlas account)",
      "list today's calendar events",
      "create calendar events with invites/location/description",
      "delete calendar events by search",
      "search contacts by name (max 5)",
      "list recent contacts (max 20)",
    ],
    cannot: [
      "send from Derek's email (only draft)",
      "search email by custom query (only unread inbox)",
      "read attachments",
      "modify existing calendar events (only create/delete)",
      "modify contacts",
      "access Atlas inbox",
    ],
    module: "src/google.ts",
  },
  {
    section: "TMAA Google Suite",
    description: "OAuth2 for The Medical Aesthetics Association (theoffice@medicalaestheticsassociation.com + derekgdicamillo@gmail.com)",
    can: [
      "list unread TMAA emails (up to 10)",
      "read full TMAA email body by ID",
      "create drafts in theoffice@MAA inbox",
      "send email from theoffice@MAA",
      "send calendar invites with .ics from theoffice@MAA",
      "list today's TMAA calendar events",
      "create TMAA calendar events with invites/location/description",
      "delete TMAA calendar events by search",
      "search TMAA contacts by name (max 5)",
      "list recent TMAA contacts (max 20)",
      "search TMAA Google Drive files",
      "list TMAA Drive folder contents",
      "download TMAA Drive file content (text, docs, sheets)",
      "read Google Sheets data (any TMAA spreadsheet)",
      "write/update Google Sheets data",
      "append rows to Google Sheets",
      "list sheet tabs in a spreadsheet",
    ],
    cannot: [
      "send from Derek's Gmail via TMAA (only theoffice)",
      "modify existing calendar events (only create/delete)",
      "upload files to Drive (read-only)",
      "GA4 Analytics (needs TMAA_GA4_PROPERTY_ID env var)",
      "YouTube management (needs TMAA_YOUTUBE_CHANNEL_ID env var)",
      "Google Ads (needs TMAA_GOOGLE_ADS_CUSTOMER_ID env var)",
    ],
    module: "src/tmaa.ts",
    tags: [
      "[TMAA_DRAFT: to=addr | subject=Subj | body=Body]",
      "[TMAA_SEND: to=addr | subject=Subj | body=Body]",
      "[TMAA_CAL_ADD: title=Title | date=YYYY-MM-DD | time=HH:MM | duration=60 | invite=email]",
      "[TMAA_CAL_REMOVE: search text]",
    ],
  },
  {
    section: "Dashboard",
    description: "Supabase business_scorecard (primary) + GHL direct (pipeline) + legacy API (fallback)",
    can: [
      "financials (revenue, COGS, expenses, P&L, balance sheet, monthly trend, unit economics) via Supabase + QuickBooks API",
      "QuickBooks read-only API: P&L, balance sheet, revenue trends, class-based filtering, cash on hand (OAuth2, Supabase token storage)",
      "pipeline stats (stages, close rate, show rate, stale leads) via GHL direct",
      "overview (leads, ad spend, CTR, CPL) via Supabase daily aggregates + GHL",
      "deep financials (category breakdown, anomaly detection) via Supabase + QB",
      "financial anomaly detection",
    ],
    cannot: [
      "write to QuickBooks (read-only API access)",
      "modify any records",
      "speed-to-lead (removed from dashboard, not in scorecard)",
      "attribution by source (removed from dashboard, not in scorecard)",
    ],
    commands: "/finance [deep], /pipeline, /scorecard, /pulse, /leads [days], /stl, /ops",
    module: "src/dashboard.ts, src/metrics-engine.ts",
  },
  {
    section: "GBP (Google Business Profile)",
    description: "read-only (API posts rejected by Google)",
    can: [
      "read reviews (count, rating, distribution, unreplied, 30d velocity, recent snippets)",
      "performance metrics (impressions, clicks, calls, directions, bookings, search vs maps split)",
      "top 20 search keywords",
    ],
    cannot: ["create local posts (Google rejects API-created posts, must use GBP dashboard)", "reply to reviews", "modify business info", "manage photos or hours"],
    module: "src/gbp.ts",
  },
  {
    section: "GA4 (Google Analytics)",
    description: "read-only",
    can: [
      "sessions, users, new users, pageviews, bounce/engagement rate",
      "traffic sources, landing pages",
      "conversions (8 event types)",
      "daily trend with WoW comparison",
      "real-time active users",
    ],
    cannot: ["modify configuration or data"],
    module: "src/analytics.ts",
  },
  {
    section: "Meta Ads",
    description: "Graph API v21.0 (read + write via ads_management token)",
    can: [
      "account summary (spend, impressions, clicks, CTR, CPC, CPL, reach, frequency, conversions)",
      "campaign breakdown (status, spend, conversions per campaign)",
      "top ads by CPL",
      "ad creative details (title, body, CTA, image URL)",
      "inline frequency/CPL/LP-CVR health flags in /ads output",
      "rename ads (single or batch)",
      "update ad status (ACTIVE/PAUSED/ARCHIVED)",
      "list ads in an ad set",
      "copy ads between ad sets (reuses creative IDs)",
    ],
    cannot: [
      "create campaigns or ad sets from scratch",
      "modify budgets",
      "upload new creatives",
      "modify targeting",
    ],
    commands: "/ads [today|7d|30d|mtd], /adspend [range], /topcreative [range] [count]",
    notes: "MONITORING: frequency >3.0 flagged in /ads output (warning) and >4.0 (danger). CPL >$65 flagged. LP CVR <5% flagged.",
    module: "src/meta.ts",
  },
  {
    section: "Care Plan",
    description: "GLP-1 weight management care plan generator",
    can: [
      "parse patient data from free text (body comp, labs, meds, symptoms)",
      "analyze composition trends",
      "map to 5-Pillar framework",
      "recommend adjunct therapies",
      "generate side effect management",
      "build escalation pathway",
    ],
    cannot: [],
    commands: "/careplan <paste patient data> or /careplan demo",
    module: "src/careplan.ts",
  },
  {
    section: "Fitness Coach",
    description: "Personal training, nutrition, workout logging via Hevy",
    can: [
      "generate DUP periodized workout plans (4-day Upper/Lower PHUL hybrid)",
      "calculate/adjust macros (recomp protocol with carb cycling)",
      "log workouts via Hevy MCP (create/read routines, exercises, workout history)",
      "weekly check-ins (weight, sleep, energy, soreness, stress)",
      "progressive overload tracking",
      "deload recommendations",
      "exercise substitutions for tall lifter biomechanics (6'4\")",
      "USDA FoodData Central macro lookups",
    ],
    cannot: ["modify Hevy account settings", "access other users' data", "prescribe medical interventions"],
    commands: "/coach or /fitness to activate fitness mode",
    state: "data/fitness/derek-profile.json (stats, macros, supplements), data/fitness/check-ins/ (weekly logs), data/fitness/programs/ (mesocycles)",
    notes: "MCP: hevy-mcp (npx, API key in env)",
    module: "src/relay.ts (fitness handler)",
  },
  {
    section: "Memory & Search",
    description: "Supabase-backed semantic search + graph",
    can: [
      "semantic hybrid search (vector + full-text RRF) across messages/memory/documents/summaries",
      "ingest documents (chunked, deduped by SHA-256)",
      "ingest entire folders via [INGEST_FOLDER:] tag or /ingest folder command (supports .txt/.md/.pdf/.docx)",
      "CRUD entities and relationships in graph (6 types: person, org, program, tool, concept, location)",
      "browse graph by type",
    ],
    cannot: ["delete indexed content", "delete entities or edges"],
    module: "src/search.ts, src/graph.ts",
  },
  {
    section: "Executive Intelligence",
    description: "cross-source synthesis (read-only)",
    can: [
      "full-funnel metrics (ad spend through profit per patient)",
      "cross-source anomaly detection (15+ checks across financial/pipeline/ads/ops/reputation/website/lead-volume)",
      "channel scorecards with efficiency ratings",
      "weekly executive push",
      "auto-generated key insights",
      "lead volume WoW trend detection",
      "zero-lead day alerts",
      "ad frequency monitoring (30d, alert >3.0, critical >4.0)",
      "CPL monitoring (7d rolling, alert >$65)",
      "LP conversion rate monitoring (alert <5%)",
      "CTR fatigue detection (<1.5%)",
    ],
    cannot: ["modify underlying source data"],
    commands: "/executive [week|month], /alerts [hours], /channels, /weekly",
    module: "src/executive.ts",
  },
  {
    section: "Lead Pipeline Automation",
    description: "auto-enrichment, reactivation, monitoring",
    can: [
      "auto-enrich new leads from GHL webhook events (research + draft outreach via workflow)",
      "source-tag new leads for attribution",
      "reactivate stale leads (7-14 days idle) with personalized re-engagement",
      "draft no-show follow-up messages via workflow",
      "track daily lead volume with source breakdown (data/lead-volume.json)",
      "alert on lead volume drops (>40% below 7d avg) and zero-lead business days",
      "detect WoW lead volume trends in executive anomaly scan",
    ],
    cannot: [],
    runs: "lead-enrich every 10 min (business hours), stale-leads at 10AM/3PM weekdays, lead-volume at 8PM daily",
    tags: "source:<channel>, auto-enriched, reactivation-attempted",
    state: "data/lead-volume.json (90-day rolling log with source attribution)",
    notes: "WORKFLOWS: new-lead-enrich (2-step: research + draft), stale-lead-reactivate (1-step: draft), no-show-followup (1-step: draft)",
    module: "src/cron.ts (lead enrichment)",
  },
  {
    section: "Subagents",
    description: "Claude Code CLI sub-processes",
    can: [
      "spawn research tasks (sonnet, fire-and-forget)",
      "spawn code agents (opus, 200 tools, 90 min default, per-task timeout override, $5 budget cap)",
      "max 8 concurrent",
      "task persistence across restarts",
    ],
    cannot: ["run tasks with credentials subagents don't have access to"],
    module: "src/supervisor.ts",
  },
  {
    section: "Persistent Process Pool",
    description: "Long-lived Claude CLI subprocesses for interactive messages",
    can: [
      "persistent Claude CLI process per agent (Atlas, Ishtar) — eliminates cold starts",
      "prompt cache reuse across turns (--resume on restart)",
      "streaming responses via NDJSON pipe",
      "auto-restart with exponential backoff on crash (max 5 attempts)",
      "30-min idle auto-shutdown to save resources",
      "feature flag: PERSISTENT_PROCESS_ENABLED (env var, default true)",
    ],
    cannot: [],
    commands: "/procstatus (show process state)",
    module: "src/persistent-process.ts, src/persistent-pool.ts",
  },
  {
    section: "Night Shift",
    description: "Autonomous overnight work",
    can: [
      "generate prioritized overnight task queue (Haiku planner at 10 PM)",
      "execute tasks with budget caps (worker at 10:15 PM)",
      "research, analysis, content drafts, learning queue items, self-improvement tasks",
    ],
    cannot: [],
    runs: "planner 10:00 PM, worker 10:15 PM (daily)",
    state: "data/night-shift-queue.json (current queue), data/night-shift-history.json (90-day log), data/learning-queue.json (knowledge gaps)",
    notes: "BUDGET: $5/night max, $2/task max, 5 tasks/night max, diminishing returns detection (stops after 2 consecutive low-value outputs). REPORT: included in 6 AM morning brief",
    module: "src/night-shift.ts",
  },
  {
    section: "Learning Queue",
    description: "Knowledge gap tracking",
    can: [
      "auto-detect knowledge gaps during conversations",
      "queue topics for overnight research",
      "track completion",
    ],
    cannot: [],
    tags: "use addToLearningQueue() from night-shift.ts to add items programmatically",
    state: "data/learning-queue.json (max 50 pending items, dedup by topic)",
    module: "src/night-shift.ts",
  },
  {
    section: "Institutional Memory (Codex)",
    description: "Agent lessons learned",
    can: [
      "record lessons from completed agent tasks (exit interviews)",
      "search lessons by keyword similarity",
      "inject top 5 relevant lessons into future agent prompts",
      "decay stale entries (30-day half-life)",
    ],
    cannot: [],
    state: "data/codex.json (entries with confidence scores, keyword matching, anti-pattern detection)",
    notes: "MAINTENANCE: 3:15 AM nightly decay pass",
    module: "src/codex.ts",
  },
  {
    section: "Content Critic",
    description: "Quality gate for generated content",
    can: [
      "evaluate content for brand voice, compliance, engagement, accuracy (Haiku, ~$0.002/eval)",
      "flag banned equipment mentions",
      "detect AI-sounding language",
      "check framework name accuracy",
    ],
    cannot: [],
    runs: "after every content waterfall generation",
    notes: "SCORES: brandVoice, compliance (2x weight), engagement, accuracy (each 0-1, threshold 0.7)",
    module: "src/content-critic.ts",
  },
  {
    section: "Agent Telemetry",
    description: "Progress tracking and event logging",
    can: [
      "progress notes: data/task-progress/{taskId}.json (checkpoint every 60s, 7-day retention)",
      "event logs: data/agent-events/{taskId}.jsonl (every tool call/decision, 14-day retention)",
      "supervisor lock: data/supervisor.lock (mutex for tasks.json, 30s TTL)",
    ],
    cannot: [],
    module: "src/progress-notes.ts, src/agent-events.ts, src/supervisor-lock.ts",
  },
  {
    section: "Strategic Weekly Memo",
    description: "Sonnet-powered weekly synthesis",
    can: [
      "synthesize week's journals, metrics, night shift outputs, and business context into 3-point actionable strategic memo (Sonnet, ~$0.75/week)",
    ],
    cannot: [],
    runs: "Saturday 9 PM",
    notes: "OUTPUT: data/task-output/weekly-strategic-memo-{date}.md + Telegram message",
    module: "src/strategic-memo.ts",
  },
  {
    section: "Overnight Content Drafts",
    description: "Auto-generated content waterfall",
    can: [
      "generate next day's content waterfall draft at 11:30 PM",
      "auto-run content critic for quality gate",
      "save to data/task-output/overnight-content-{date}.md",
    ],
    cannot: [],
    runs: "11:30 PM daily",
    depends: "content-critic.ts (Haiku quality gate), prompt-runner.ts",
    module: "src/cron.ts (overnight content)",
  },
  {
    section: "Task Persistence",
    description: "Supabase-backed agent survival",
    can: [
      "dual-write task state to local JSON + Supabase",
      "sync on startup",
      "auto-abandon tasks running >2 hours",
      "recover orphaned tasks after restart",
    ],
    cannot: [],
    notes: "TABLE: agent_tasks (id, type, description, status, model, prompt, output_file, cost_usd, started_at, metadata). INIT: initTaskPersistence() called in startCronJobs(), syncTasksFromSupabase() runs on startup",
    module: "src/task-persistence.ts",
  },
  {
    section: "Model Router",
    description: "Tiered model selection",
    can: [
      "route tasks to Haiku/Sonnet/Opus based on task type and complexity",
      "estimate complexity via Haiku ($0.01/call)",
      "auto-route convenience function",
    ],
    cannot: [],
    notes: "CATEGORIES: monitoring (Haiku), content/research (Sonnet), complex code (Opus). USAGE: routeModel(taskType, complexity) or autoRoute(taskType, description)",
    module: "src/model-router.ts",
  },
  {
    section: "Shared Memory",
    description: "Cross-agent visibility",
    can: [
      "mark memory entries as shared (visible to both Atlas and Ishtar)",
      "query shared memories",
    ],
    cannot: [],
    notes: "TABLE: memory.shared column (boolean, default false)",
    module: "src/shared-memory.ts",
  },
  {
    section: "Darwin Loop",
    description: "Performance optimization",
    can: [
      "record task performance metrics (duration, cost, quality)",
      "discover optimal config per task category",
      "90-day retention",
    ],
    cannot: [],
    state: "data/darwin-records.json",
    module: "src/darwin.ts",
  },
  {
    section: "Agent Blackboard",
    description: "Swarm coordination",
    can: ["shared key-value store for agents within a swarm", "upsert on (swarm_id, key)"],
    cannot: [],
    notes: "TABLE: agent_blackboard (swarm_id, agent_id, key, value JSONB)",
    module: "src/blackboard.ts",
  },
  {
    section: "Show Rate Engine",
    description: "Automated appointment reminders + no-show recovery",
    can: [
      "scan upcoming appointments (4-day window)",
      "send tiered reminders via GHL tags (72h confirmation, 24h logistics, 2h final nudge)",
      "detect no-shows and trigger same-day recovery outreach + auto-draft personalized re-engagement via no-show-followup workflow",
      "create staff follow-up tasks for unconfirmed patients",
      "tag contacts at each reminder stage for GHL workflow triggers",
      "daily digest of reminder activity (yesterday + today)",
      "stale tag cleanup",
    ],
    cannot: [],
    runs: "every 15 min during business hours (7am-8pm Mon-Sat) via cron job \"appointment-reminders\"",
    tags: "atlas-reminder-72h, atlas-reminder-24h, atlas-reminder-2h, atlas-noshow-recovery, atlas-appointment-confirmed",
    depends: "GHL workflows must be configured to fire SMS/email when Atlas tags are applied. Atlas handles timing/logic, GHL handles patient-facing delivery.",
    state: "data/show-rate-state.json (sent records, daily stats, 14-day retention)",
    module: "src/show-rate.ts",
  },
  {
    section: "Website (pvmedispa.com)",
    description: "WP REST API + Local Dev",
    can: [
      "list pages (slug, title, id)",
      "get page content by slug or ID",
      "update page content by slug",
      "create blog posts (draft or publish)",
      "list/resolve categories",
      "list recent posts",
      "list media",
      "get custom CSS",
    ],
    cannot: [
      "upload media (planned)",
      "delete pages/posts",
      "modify plugins or theme settings",
      "manage users or WP options",
    ],
    tags: "[WP_UPDATE: page-slug | HTML content], [WP_POST: title | content | status=draft | categories=cat1,cat2]",
    notes: "SAFETY: WP_POST defaults to draft. WP_UPDATE requires user confirmation. Always back up before overwriting.\nLOCAL DEV: C:\\Users\\Derek DiCamillo\\Local Sites\\pv-medispa-weight-loss\\ (Local by Flywheel, Kadence theme, WP-CLI via wp.sh)\nDEPLOY: WP Engine Git Push for theme/code changes",
    module: "src/website.ts",
  },
  {
    section: "Planner (Microsoft)",
    description: "Graph API via M365 integration",
    can: [
      "list plans across all M365 groups",
      "create plans",
      "list/create buckets",
      "list/create/update/complete tasks",
      "get task details (description, notes)",
      "move tasks between buckets",
      "assign tasks to users",
      "set due dates and priority",
      "Kanban board view for Telegram",
    ],
    cannot: [
      "delete plans/buckets/tasks",
      "manage Planner categories/labels",
      "set recurrence",
      "add attachments or checklist items",
      "access Planner outside of M365 groups",
    ],
    commands: "`/planner` (list all), `/planner <name>` (board view), `/planner add <plan> | <bucket> | <task>`, `/planner move <task> | <bucket>`, `/planner done <task>`",
    tags: "`[PLANNER_TASK: plan=X | bucket=X | title=X | assignee=email | due=YYYY-MM-DD | description=text]`, `[PLANNER_MOVE: task=X | bucket=X | plan=X]`, `[PLANNER_DONE: task=X | plan=X]`",
    requires: "Tasks.ReadWrite permission in Azure portal (must be added manually). Group.ReadWrite.All already present.",
    notes: "NOTE: Planner PATCH operations require If-Match ETag headers. The integration handles etag fetching automatically.",
    module: "src/m365.ts",
  },
  {
    section: "Home Assistant",
    description: "REST API (Nabu Casa remote + local fallback)",
    can: [
      "list all entities by domain",
      "get entity state/attributes",
      "turn on/off/toggle lights/switches/fans",
      "lock/unlock doors",
      "set thermostat temperature/mode/fan",
      "activate scenes",
      "trigger/enable/disable automations",
      "call any HA service",
      "get state history",
      "build dashboard summary",
    ],
    cannot: [
      "modify HA configuration",
      "install/update integrations",
      "access HA add-ons",
      "stream cameras",
      "send HA notifications (use Telegram instead)",
    ],
    module: "src/homeassistant.ts",
  },
  {
    section: "Recording Studio",
    description: "Teleprompter + OBS WebSocket",
    can: [
      "load teleprompter scripts from scripts/gamma-inputs/ (modules 00-10 + docs)",
      "start/stop/reset teleprompter scrolling",
      "set scroll speed and font size",
      "start/stop/pause/resume OBS recording",
      "switch OBS scenes",
      "get OBS recording status (timecode, active scene, scene list)",
      "serve teleprompter UI on local network (port 8585) for iPad/Surface access",
      "voice-activated scrolling via WebSpeech API (Chrome only)",
    ],
    cannot: [
      "upload media to OBS",
      "modify OBS settings (audio, video, filters)",
      "stream (recording only)",
      "access OBS on remote machines",
    ],
    commands: "/record (status), /record <module> (load script), /record start (record + scroll), /record stop, /record pause, /record resume",
    requires: "OBS open with WebSocket server enabled (Tools > WebSocket Server Settings), OBS_WS_PASSWORD in .env, teleprompter server running (pm2 start teleprompter or bun run teleprompter/server.ts)",
    notes: "SERVER: teleprompter/server.ts (Bun, port 8585), teleprompter/index.html (web UI). MODULE: src/obs.ts (obs-websocket-js wrapper)",
    module: "src/obs.ts",
  },
  {
    section: "Security & Access Control",
    description: "Telegram user ID-based",
    can: [
      "AUTH: Telegram user ID allowlist via config/agents.json (per-agent). No IP-based auth or rate limiting",
      "RATE LIMITING: Message dedup keyed on userId + text (5 min window). Alert emission capped at 10/hour (critical exempt). Claude model fallback on API 429s (opus -> sonnet -> haiku). Circuit breakers on external APIs (GHL, Google, Meta, Dashboard)",
    ],
    cannot: [],
    notes: "NOT APPLICABLE: IP-based rate-limit key normalization (OpenClaw pattern). Atlas is a Telegram bot, not an HTTP server. Telegram handles transport-layer identity.",
    module: "src/relay.ts, src/circuit-breaker.ts, src/alerts.ts",
  },
  {
    section: "Midas Marketing Intelligence",
    description: "Marketing analysis and attribution layer (src/marketing.ts)",
    can: [
      "daily funnel conversion monitor (9 AM, compares against 7-day avg, alerts on >20% drops)",
      "daily ad performance digest (9:30 PM, trend detection, entity diversity scoring, threshold alerts)",
      "weekly full-funnel attribution report (Sunday 9 AM, Meta spend -> leads -> booked -> showed -> patient -> ROAS)",
      "content hooks memo (Tue/Fri 7 AM, Opus, 3 hook ideas with framework classification)",
      "competitor recon (Wed 8 AM, Opus, watchlist analysis, threat assessment, opportunity gaps)",
      "GBP content drafts (Mon/Thu 7:30 AM, Sonnet, adapts waterfall content, requires approval)",
      "monthly strategic brief (1st at 10 AM, Opus, full creative audit + next month campaign plan + playbook update)",
      "creative analysis through 5 layers: hook type, Hormozi Value Eq, Brunson HSO, Andromeda entity diversity, visual style",
      "auto-pause ads exceeding CPL $100 for 5+ days (with alert to Derek)",
    ],
    cannot: [
      "collect raw data (uses existing ad-tracker, lead-volume, show-rate crons)",
      "modify budgets or scale spend (recommend only, requires Derek approval)",
      "publish content or GBP posts (drafts only, requires approval)",
      "access GHL directly at runtime (reads from data/*.json files)",
    ],
    runs: "midas-funnel 9 AM daily, midas-digest 9:30 PM daily, midas-attribution Sun 9 AM, midas-hooks Tue/Fri 7 AM, midas-recon Wed 8 AM, midas-gbp Mon/Thu 7:30 AM, midas-monthly 1st 10 AM",
    state: "data/marketing-state.json (funnel history, 90-day retention). Outputs: memory/marketing/content-hooks/, memory/marketing/competitors/recon-*.md, memory/marketing/attribution/monthly-brief-*.md, data/content-drafts/gbp-*.md",
    notes: "Agent file: .claude/agents/marketing.md (Opus). Knowledge base: memory/marketing/. Frameworks: Hormozi Value Equation, Brunson Hook-Story-Offer, Meta Andromeda Entity IDs.",
    module: "src/marketing.ts",
  },
  {
    section: "TMAA Newsletter Automation",
    description: "Two-tier newsletter system (free weekly + paid biweekly) via Brevo with Telegram approval gate",
    can: [
      "draft free newsletter ('This Week at TMAA') from recent blog posts + SAGE trending data + rotating CTA",
      "draft paid newsletter ('TMAA Insider') with blog recap, SAGE insights, partner spotlight, resource highlights",
      "create Brevo campaign drafts and send test emails to Derek + Esther",
      "send approved newsletters via Brevo campaign API",
      "rotate partner spotlights from tmaa_partners Supabase table",
      "rotate CTAs (Join TMAA, Try SAGE, Browse Resources) across free editions",
      "handle /approve free and /approve paid commands",
    ],
    cannot: [
      "send newsletters without explicit Telegram approval from Derek or Esther",
      "modify Brevo templates (managed in Brevo UI)",
      "manage Brevo contact lists (managed ad hoc)",
    ],
    commands: ["/approve free", "/approve paid"],
    runs: "maa-newsletter-draft Wed 8AM, maa-newsletter-free-send Sat 9AM, maa-newsletter-paid-send Sun 9AM",
    state: "data/maa-newsletter-state.json (approval flags, campaign IDs, rotation indexes)",
    module: "src/maa-newsletter.ts",
  },
  {
    section: "PV Newsletter Co-Pilot",
    description: "Collaborative weekly newsletter creation via Telegram topic thread with GHL V2 draft push",
    can: [
      "Tuesday 7 AM smart topic suggestion (blog + pillar rotation + trending news)",
      "collaborative section-by-section drafting in Newsletter topic thread",
      "voice-matched content generation (Derek's teaching style)",
      "content critic quality gate on all draft sections",
      "HTML assembly matching GHL template structure",
      "push assembled draft to GHL as draft campaign via V2 Email Campaign API",
      "tag-based recipient targeting (newsletter tag)",
      "pillar rotation tracking across weeks",
      "topic dedup (6-week lookback)",
      "Wednesday morning nudge if no response to kickoff",
      "start over, skip week, subject line override commands",
    ],
    cannot: [
      "send newsletters directly (draft only, Derek sends from GHL)",
      "include images/diagrams (text content only, images added in GHL)",
      "modify GHL email template design (content only)",
    ],
    notes: "Operates in dedicated Telegram topic thread. Env: PV_NEWSLETTER_TOPIC_ID",
    module: "src/pv-newsletter.ts",
    tags: [
      "[PV_NEWSLETTER_TOPIC: topic | pillar=Name]",
      "[PV_NEWSLETTER_SECTION: name | content]",
      "[PV_NEWSLETTER_SUBJECT: subject]",
      "[PV_NEWSLETTER_PUSH]",
      "[PV_NEWSLETTER_RESET]",
      "[PV_NEWSLETTER_SKIP]",
      "[PV_NEWSLETTER_PREVIEW]",
    ],
  },
  {
    section: "Atlas Prime - Ledger",
    description: "Tamper-evident action log (ed25519-signed, SHA-256 chained)",
    can: [
      "append tamper-evident actions to data/atlas-ledger/ (ed25519-signed, SHA-256 chained)",
      "verify full chain integrity",
      "publish hourly Merkle root to data/atlas-ledger-roots.jsonl",
    ],
    cannot: [
      "delete or mutate committed entries",
    ],
    depends: "crypto (built-in), ed25519 keys in data/atlas-ledger.{key,pub}",
    module: "src/ledger.ts",
  },
  {
    section: "Atlas Prime - Tool Gate",
    description: "Pre-dispatch invariant enforcement for externally-visible tool calls",
    can: [
      "enforce atlas.spec invariants on every externally-visible tool call before dispatch",
      "return { allowed, reason, matchedInvariant }",
    ],
    cannot: [
      "modify atlas.spec at runtime (read-only; cached after first load)",
    ],
    depends: "js-yaml, atlas.spec (project root)",
    module: "src/tool-gate.ts",
  },
  {
    section: "Atlas Prime - Staleness Sentinel",
    description: "Staleness-axis classifier for user messages",
    can: [
      "classify user messages on the staleness axis (timeless/slow/medium/fast/real_time)",
      "identify matched hot-domain + half-life",
      "force freshness-cache lookup for 'fast' and 'real_time' questions",
    ],
    cannot: [
      "modify hot-domains.json at runtime (updated by freshness-feed cron only)",
    ],
    depends: "haiku-client.ts, data/hot-domains.json",
    module: "src/staleness-sentinel.ts",
  },
  {
    section: "Atlas Prime - Freshness Feed",
    description: "Nightly refresh of llms.txt / changelog for hot domains",
    can: [
      "nightly (3 AM) refresh of llms.txt / changelog for hot domains",
      "cache to data/fresh-knowledge/<domain>.json",
      "expose readFresh(domain) for relay-side access",
    ],
    cannot: [
      "trigger on-demand refresh during a user turn (relay does WebFetch for that)",
    ],
    depends: "data/hot-domains.json",
    module: "src/freshness-feed.ts",
  },
  {
    section: "Atlas Prime - Replay Harness",
    description: "Claude-as-judge scorer over labeled past conversations. Produces groundedness, tool-correctness, and refusal-calibration scores. The fitness function every later sprint depends on.",
    can: [
      "load labeled dataset from data/replay-dataset.jsonl",
      "score entries with Haiku (3 axes: groundedness, tool-correctness, refusal-calibration)",
      "emit per-run JSON to data/replay-results/",
      "grow dataset in-conversation via [LABEL_GOOD] / [LABEL_BAD: reason] tags",
      "run nightly at 3:30 AM via cron 'replay-nightly'",
    ],
    cannot: [
      "modify dataset without explicit LABEL tag or script run",
      "score entries whose content exceeds 4000 chars (truncation applied)",
    ],
    depends: "haiku-client.ts, supabase",
    module: "src/replay-harness.ts",
  },
  {
    section: "Atlas Prime - Trust Budget",
    description: "Per-domain trust score with 30-day half-life decay. Visible to Derek via /trust. Below-threshold domains auto-escalate.",
    can: [
      "compute per-domain trust from replay + ledger events",
      "render /trust report for Telegram",
      "flag below-threshold domains for auto-escalation via shouldEscalate()",
    ],
    cannot: [
      "modify historical trust events (append-only log at data/trust-snapshots.jsonl)",
    ],
    commands: ["/trust"],
    depends: "replay-harness.ts, ledger.ts",
    module: "src/trust-engine.ts",
  },
  {
    section: "Atlas Prime - Reader (CaMeL)",
    description: "Tool-less Haiku extractor for untrusted content. Any ingested doc / webfetch / inbox body is extracted to a typed schema before the Planner sees it — raw bytes never reach a SEND tool.",
    can: [
      "extract typed fields from untrusted content (PDF, email, web page, CRM message)",
      "gate search.ts getRelevantContext() documents through renderForPlanner()",
      "fail closed on extraction error",
    ],
    cannot: [
      "call tools (no tool access by design)",
      "echo raw untrusted content into Planner prompt",
      "exceed READER_MAX_CHARS per chunk (default 40k)",
    ],
    depends: "haiku-client.ts",
    module: "src/reader.ts",
  },
  {
    section: "Atlas Prime - Post-Compact Hook",
    description: "Formal hooks fired on PreCompact (snapshot writer) and SessionStart (re-orient reminder). Permanently fixes the re-orient failure class.",
    can: [
      "write memory/compact-snapshot.md on PreCompact",
      "emit re-orient instructions on SessionStart",
    ],
    cannot: [
      "block Claude from responding (exit 0 advisory; behavior gate is prompt content)",
    ],
    depends: "scripts/pre-compact-snapshot.sh, scripts/post-compact-verify.sh",
    module: "scripts/pre-compact-snapshot.sh, scripts/post-compact-verify.sh",
  },
  {
    section: "Atlas Prime - Cortex (7-tier stack + demotion)",
    description: "Tier definitions over existing memory surfaces; attribution log; multi-signal weighted demotion (judge 0.5 + correction 1.0 + trust 0.7, threshold 3.0); inversion at depth ≤2.",
    can: [
      "record (turn_id, memory_id) pairs to attribution_log on retrieval",
      "increment demotion_pressure on failure signals",
      "demote memories at threshold and write inverted hypotheses",
      "promote 3+ episodic clusters into semantic rules nightly",
    ],
    cannot: [
      "modify identity tier (SOUL.md / IDENTITY.md / USER.md) — human-edited only",
      "exceed inversion depth 2 (alert fires for manual review)",
    ],
    module: "src/cortex.ts",
    depends: "memory, attribution_log, haiku-client.ts",
    runs: "episodic-cluster-nightly 2:30 AM, attribution-purge-nightly 4:00 AM, cortex-demote-nightly 0:30 AM",
  },
  {
    section: "Atlas Prime - Procedural Memory",
    description: "Hand-curated procedures with Beta(α,β) Bayesian posteriors. Retrieve by intent embedding + Thompson sampling. Slot-filled at use time.",
    can: [
      "find top-k procedures for a given goal via Thompson sampling",
      "record success/failure outcomes that update Beta posteriors",
      "fill {slot} placeholders from a values map",
      "seed/reseed from data/procedures-seed.yaml idempotently",
    ],
    cannot: [
      "auto-generate new procedures from conversations (Sprint 6)",
      "execute action_sequence steps directly — slot-filler returns tag strings that go through tool-gate",
    ],
    module: "src/procedures.ts",
    depends: "procedures table, procedure_outcomes table, OpenAI embeddings",
    state: "data/procedures-seed.yaml (10 starter procedures)",
  },
  {
    section: "Atlas Prime - Memory Rewriting (lazy-on-stale)",
    description: "Living summaries. Rewrites trigger when a memory is stale (>7 days since last rewrite) AND frequently accessed (≥5 reads since last rewrite). Originals immutable.",
    can: [
      "increment access_count_since_rewrite on every retrieval",
      "rewrite summary via Haiku with hindsight (AT THE TIME / AS OF format)",
      "reject rewrites failing content-critic (score <0.7 or hallucination flag)",
      "cap 50 rewrites per nightly window",
    ],
    cannot: [
      "modify original_content (frozen on backfill)",
      "rewrite memories with class='demoted'",
    ],
    module: "src/memory-rewrite.ts",
    depends: "memory.original_content, memory.summary, content-critic.ts, haiku-client.ts",
    runs: "memory-rewrite-nightly at 1:00 AM",
  },
  {
    section: "Atlas Prime - Reranker + Contextual Chunking",
    description: "Retrieval pipeline: embedding top-50 → reranker top-8. Local Transformers.js (zerank-1-small if accessible, else bge-reranker-base fallback). New ingestions get contextual preambles.",
    can: [
      "rerank up to 50 candidates with cross-encoder relevance scores",
      "log rerank_score to attribution_log for debugging",
      "generate ≤80-token Haiku preamble per chunk during ingestion",
      "backfill existing documents to chunked_strategy='contextual-v1'",
      "pre-warm model 30s after boot",
    ],
    cannot: [
      "load zerank-1-small without HF_TOKEN + access (gated; fallback to bge automatic)",
      "retry inference on per-pair failure (returns score 0)",
    ],
    module: "src/reranker.ts, src/ingest-worker.ts",
    depends: "@xenova/transformers, OpenAI embeddings",
  },
  {
    section: "Atlas Prime - Causal DAG",
    description: "Explainable causal graph of business state. Three discovery paths (PC algo, LLM-proposed, natural-experiment). Derek-approval gate; falsification preserves audit history.",
    can: [
      "find causes for a metric (findCauses)",
      "find effects from an action (findEffects)",
      "walk a reasoning chain between two nodes (walkPath)",
      "list pending hypothesized edges (pendingApprovals)",
      "approve / falsify edges via /dag commands",
      "discover edges from intervention pre/post deltas (natural-experiment)",
      "discover statistical edges via PC algorithm + bootstrap stability",
      "propose semantic edges via Opus (LLM-proposed) with evidence-pointer gate",
    ],
    cannot: [
      "auto-execute or apply edges without Derek approval (except natural-experiment which lands status='observed' but still approved=false)",
      "run PC algorithm without Python + causaldag installed",
    ],
    module: "src/causal-graph.ts, src/causal-discovery.ts",
    depends: "Supabase (causal_nodes/edges/observations), Python (causaldag), Opus, ledger",
    commands: ["/dag pending", "/dag approve", "/dag falsify", "/dag walk", "/dag stats"],
    runs: "causal-natural-experiments daily 0:30, causal-pc-discovery weekly 1:30, causal-llm-propose Sundays 2:00",
  },
  {
    section: "Atlas Prime - World Model",
    description: "Foundation forecaster (Chronos-Bolt) + Causal-DAG action effects. Counterfactual forecasts cite specific DAG edges as audit chain.",
    can: [
      "unconditional p05/p50/p95 forecasts from scorecard history (forecast)",
      "counterfactual forecasts conditioned on a DAG action (forecastCounterfactual)",
      "persist forecast rows for audit (world_model_forecasts)",
      "compose Haiku reasoning paragraph citing DAG edge IDs",
    ],
    cannot: [
      "train custom Dreamer-style RL (uses pre-trained Chronos)",
      "forecast metrics not present in business_scorecard",
      "apply unfounded action effects (only approved DAG edges)",
    ],
    module: "src/world-model.ts, scripts/chronos_forecast.py",
    depends: "Python chronos-forecasting, Causal DAG (findEffects)",
    commands: ["/forecast"],
    state: "world_model_forecasts table (audit cache)",
  },
  {
    section: "Atlas Prime - Dream Engine",
    description: "Two-phase nightly imagination. SWS replays high-salience episodes with counterfactual variants and emits semantic rules. REM simulates tomorrow scenarios from the uncertainty pool, scored by unprep_score.",
    can: [
      "compute composite salience over memory (access + trust + incident + demotion)",
      "SWS counterfactual variant generation + abstract rule writing + DOUBT detection",
      "REM tomorrow scenarios via Opus, validated by World Model forecasts",
      "write nightly memory/dreams/YYYY-MM-DD-{sws,rem}.md narratives",
      "embed dreams for retrieval; surface in next morning brief",
    ],
    cannot: [
      "modify the original memories (immutable; rules emit as new semantic-class memory rows)",
      "execute actions or send messages -- dreams are reflective only",
    ],
    module: "src/dream-engine.ts",
    depends: "memory + attribution_log + procedures + trust + Causal DAG + World Model",
    commands: ["/dreams", "/dreams sws", "/dreams search <topic>"],
    runs: "dream-sws-nightly 23:00, dream-rem-nightly 03:00",
    state: "memory/dreams/*.md (human readable) + dreams table (retrievable)",
  },
  {
    section: "Atlas Prime - Derek Twin",
    description: "Stated/revealed preference model. Tracks gap between what users say they want and what they actually do. Morning predictions + evening self-score = implicit reward signal for Sprint 6 self-improvement.",
    can: [
      "classify user followups as accept/rewrite_align/rewrite_diverge/reject",
      "recompute divergence per preference per domain",
      "alert on gap > 0.4 with sample_size >= 5",
      "generate 3-5 morning predictions per user via Opus",
      "score each prediction in evening via Haiku-as-judge against today's user turns",
      "report 30-day rolling calibration",
    ],
    cannot: [
      "modify stated preferences automatically -- only via /twin update",
      "predict beyond ~5 items per morning",
    ],
    module: "src/derek-twin.ts",
    depends: "messages + Opus + Haiku + USER.md (initial seed)",
    commands: ["/twin", "/twin predictions", "/twin divergence", "/twin reconcile", "/twin update", "/twin hold", "/twin calibration"],
    runs: "twin-update-nightly 22:30, twin-predict-morning 05:30, twin-score-evening 21:00",
    state: "twin_stated_preferences, twin_revealed_observations, twin_divergence, twin_predictions, data/twin-calibration.jsonl",
  },
];

/**
 * Register all capability declarations. Called once on startup.
 */
export function registerAllCapabilities(): void {
  for (const cap of ALL_CAPABILITIES) {
    registerCapabilities(cap);
  }
}
